name: a-pr-checks

on:
  pull_request:
    types: [ edited, opened, synchronize, reopened ]
    branches: 
      - 'master'
      - 'main'
      - 'dev'
    paths-ignore:
      - '**.yaml'
      - '**.md'
      - '**.sh'
      - 'website/*'
      - 'examples/*'
      - 'docs/*'
      - 'build/*'
      - '.github/*'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

  
jobs:
  test:
    uses: ./.github/workflows/00-pr-scanner.yaml
    with:
      release: ${{ github.ref_name}}
      client: test
