name: c-create_release
on:
  workflow_call:
    inputs:
      RELEASE_NAME:
        description: 'Release name'
        required: true
        type: string
      TAG:
        description: 'Tag name'
        required: true
        type: string
      DRAFT:
        description: 'Create draft release'
        required: false
        type: boolean
        default: false

jobs:

  create-release:
    name: create-release
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write    
    steps:
      - uses: actions/download-artifact@v3.0.2
        id: download-artifact
        with:
          path: .

      - name: ls -la after dl
        run: ls -la
      
      - name: ls -laR after dl
        run: ls -laR

      - name: artifacts rename
        run: |

          MAC_OS=macos-latest
          UBUNTU_OS=ubuntu-latest
          WINDOWS_OS=windows-latest

          mv ./kubescape-$MAC_OS/kubescape ./kubescape-$MAC_OS/kubescape-$MAC_OS-${{ inputs.TAG }}
          mv ./kubescape-$MAC_OS/kubescape.sha256 ./kubescape-$MAC_OS/kubescape-$MAC_OS-${{ inputs.TAG }}.sha256

          mv ./kubescape-$UBUNTU_OS/kubescape ./kubescape-$UBUNTU_OS/kubescape-$UBUNTU_OS-${{ inputs.TAG }}
          mv ./kubescape-$UBUNTU_OS/kubescape.sha256 ./kubescape-$UBUNTU_OS/kubescape-$UBUNTU_OS-${{ inputs.TAG }}.sha256

          mv ./kubescape-$WINDOWS_OS/kubescape ./kubescape-$WINDOWS_OS/kubescape-$WINDOWS_OS-${{ inputs.TAG }}
          mv ./kubescape-$WINDOWS_OS/kubescape.sha256 ./kubescape-$WINDOWS_OS/kubescape-$WINDOWS_OS-${{ inputs.TAG }}.sha256

      - name: ls -la after RENAME
        run: ls -la
      
      - name: ls -laR after RENAME
        run: ls -laR

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.RELEASE_NAME }}
          TAG: ${{ inputs.TAG }}
          body: ${{ github.event.pull_request.body }}
          draft: ${{ inputs.DRAFT }}
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            ./kubescape-ubuntu-latest/*
            ./kubescape-macos-latest/*
            ./kubescape-windows-latest/*
            
      - name: Digest
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha1
          file-name: kubescape-release-digests