name: c-create_release
on:
  workflow_call:
    inputs:
      RELEASE_NAME:
        description: 'Release name'
        required: true
        type: string
      TAG_NAME:
        description: 'Tag name'
        required: true
        type: string
      DRAFT:
        description: 'Create draft release'
        required: false
        type: boolean
        default: false

jobs:

  create-release:
    name: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/download-artifact@v3.1.2
        id: download-artifact
        with:
          path: .

      - name: ls -la after dl
        run: ls -la
      
      - name: ls -laR after dl
        run: ls -laR

      - name: artifacts rename
        run: |

          MAC_OS=macos-latest
          UBUNTU_OS=ubuntu-latest
          WINDOWS_OS=windows-latest

          mv ./kubescape-$MAC_OS-${{ inputs.TAG_NAME }}/kubescape ./kubescape-$MAC_OS-${{ inputs.TAG_NAME }}/kubescape-$MAC_OS-${{ inputs.TAG_NAME }}
          mv ./kubescape-$MAC_OS-${{ inputs.TAG_NAME }}/kubescape.sha256 ./kubescape-$MAC_OS-${{ inputs.TAG_NAME }}/kubescape-$MAC_OS-${{ inputs.TAG_NAME }}.sha256

          mv ./kubescape-$UBUNTU_OS-${{ inputs.TAG_NAME }}/kubescape ./kubescape-$UBUNTU_OS-${{ inputs.TAG_NAME }}/kubescape-$UBUNTU_OS-${{ inputs.TAG_NAME }}
          mv ./kubescape-$UBUNTU_OS-${{ inputs.TAG_NAME }}/kubescape.sha256 ./kubescape-$UBUNTU_OS-${{ inputs.TAG_NAME }}/kubescape-$UBUNTU_OS-${{ inputs.TAG_NAME }}.sha256

          mv ./kubescape-$WINDOWS_OS-${{ inputs.TAG_NAME }}/kubescape ./kubescape-$WINDOWS_OS-${{ inputs.TAG_NAME }}/kubescape-$WINDOWS_OS-${{ inputs.TAG_NAME }}
          mv ./kubescape-$WINDOWS_OS-${{ inputs.TAG_NAME }}/kubescape.sha256 ./kubescape-$WINDOWS_OS-${{ inputs.TAG_NAME }}/kubescape-$WINDOWS_OS-${{ inputs.TAG_NAME }}.sha256

      - name: ls -la after RENAME
        run: ls -la
      
      - name: ls -laR after RENAME
        run: ls -laR

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.RELEASE_NAME }}
          tag_name: ${{ inputs.TAG_NAME }}
          body: ${{ github.event.pull_request.body }}
          draft: ${{ inputs.DRAFT }}
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            ./kubescape-ubuntu-latest-${{ inputs.TAG_NAME }}/*
            ./kubescape-macos-latest-${{ inputs.TAG_NAME }}/*
            ./kubescape-windows-latest-${{ inputs.TAG_NAME }}/*